/**
 * The README files of the profile repository, one per language: only images
 * and links, so GitHub's sanitiser keeps everything. Each image has a light
 * and a dark file; the <picture> element picks one from the viewer's GitHub
 * theme. A row of language pills on top links the READMEs to each other.
 */
const attr = (text) => String(text).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;')

/** README.md is English and shows on the profile page; README.<code>.md holds each other language. */
export const readmeName = (code) => (code === 'en' ? 'README.md' : `README.${code}.md`)

/** A themed image from `dir`. `width` keeps two cards side by side on desktop and lets them wrap on phones. */
function picture(dir, frame, width, href = frame.href) {
  return [
    `<a href="${attr(href)}"><picture>`,
    `<source media="(prefers-color-scheme: dark)" srcset="${dir}/${frame.id}-dark.svg" />`,
    `<img src="${dir}/${frame.id}-light.svg" width="${width}" alt="${attr(frame.alt)}" />`,
    '</picture></a>',
  ].join('')
}

export function buildReadme({ lang, frames, pills, rows, sizes, content }) {
  const { githubProfile: gp, languages, profile, site } = content
  const dir = `assets/${lang}`
  const byId = Object.fromEntries(frames.map((f) => [f.id, f]))
  const show = (id) => picture(dir, byId[id], sizes[id].width)
  const buttons = frames.filter((f) => f.id.startsWith('button-')).map((f) => show(f.id))
  const languageRow = languages.map(({ code }) => {
    const pill = pills.find((p) => p.code === code && p.on === (code === lang))
    const href = code === 'en' ? gp.profile : `${gp.repository}/blob/main/${readmeName(code)}`
    return picture('assets/lang', pill, sizes[pill.id].width, href)
  })

  return `<!--
  Generated by \`npm run github-profile\` in ${site.source}
  from src/data/profile.ts. Edit the data there and regenerate; do not edit this file.
  .github/workflows/age.yml redraws the age in assets/*/glance-*.svg every day.
-->

<p align="center">
${languageRow.join('\n')}
</p>

<p align="center">
${picture(dir, byId.hero, '100%')}
</p>

<p align="center">
${buttons.join('\n')}
</p>

<p align="center"><code>${attr(profile.email)}</code></p>

${rows.map((row) => `<p align="center">\n${row.map(show).join('\n')}\n</p>`).join('\n\n')}

<p align="center">
${picture(dir, byId.footer, '100%')}
</p>
`
}
