/**
 * README.md of the profile repository: only images and links, so GitHub's
 * sanitiser keeps everything. Each image has a light and a dark file; the
 * <picture> element picks one from the viewer's GitHub theme.
 */
const attr = (text) => String(text).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;')

/** A themed image. `width` keeps two cards side by side on desktop and lets them wrap on phones. */
function picture(frame, width) {
  const img = `<img src="assets/${frame.id}-light.svg" width="${width}" alt="${attr(frame.alt)}" />`
  return [
    `<a href="${attr(frame.href)}"><picture>`,
    `<source media="(prefers-color-scheme: dark)" srcset="assets/${frame.id}-dark.svg" />`,
    img,
    '</picture></a>',
  ].join('')
}

export function buildReadme({ frames, rows, sizes, content }) {
  const byId = Object.fromEntries(frames.map((f) => [f.id, f]))
  const show = (id) => picture(byId[id], sizes[id].width)
  const buttons = frames.filter((f) => f.id.startsWith('button-')).map((f) => show(f.id))

  return `<!--
  Generated by \`npm run github-profile\` in ${content.site.source}
  from src/data/profile.ts. Edit the data there and regenerate; do not edit this file.
  .github/workflows/age.yml redraws the age in assets/glance-*.svg every day.
-->

<p align="center">
${picture(byId.hero, '100%')}
</p>

<p align="center">
${buttons.join('\n')}
</p>

<p align="center"><code>${attr(content.profile.email)}</code></p>

${rows.map((row) => `<p align="center">\n${row.map(show).join('\n')}\n</p>`).join('\n\n')}

<p align="center">
${picture(byId.footer, '100%')}
</p>
`
}
