/**
 * Generated by `npm run github-profile` in jumincho/juminwho. Do not edit here.
 *
 * Runs every day in .github/workflows/age.yml: recomputes Jumin's age and
 * redraws the digits in each language's glance card. The digits are outlined
 * glyphs with fixed ids (age-0 … age-9, age-dot) and equal widths, so this
 * only rewrites the <use> elements inside <g id="age">, whose data-digit and
 * data-dot give the advances in font units; no fonts are needed.
 */
import { readFile, writeFile } from 'node:fs/promises'

const BIRTH = '__BIRTH__'
const FILES = ['__FILES__']
const YEAR_MS = 365.2425 * 24 * 60 * 60 * 1000
const age = ((Date.now() - Date.parse(BIRTH)) / YEAR_MS).toFixed(4)

for (const file of FILES) {
  const svg = await readFile(file, 'utf8')
  if (!svg.includes('<g id="age"')) throw new Error(`No age digits found in ${file}`)
  const next = svg.replace(/<g id="age"([^>]*)>.*?<\/g>/s, (_, attrs) => {
    const read = (name) => Number(attrs.match(new RegExp(`data-${name}="([^"]+)"`))[1])
    let x = 0
    const uses = [...age].map((ch) => {
      const use = `<use href="#age-${ch === '.' ? 'dot' : ch}" x="${x}"/>`
      x += ch === '.' ? read('dot') : read('digit')
      return use
    })
    return `<g id="age"${attrs}>${uses.join('')}</g>`
  })
  await writeFile(file, next)
}

console.log(`age = ${age} (${FILES.length} files)`)
